server:
  port: 8080

# Configuration Spring
spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml
    enabled: true

# Configuration Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: INFO