server:
  port: 8080

# Configuration Spring
spring:

  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml
    enabled: true

# Configuration Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: INFO