services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: studentpass
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: studentpass
      APP_USER: student
      APP_USER_PASSWORD: studentpass
      ORACLE_DATABASE: XEPDB1
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
