version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace/control-academico_student-service:cached
    command: sleep infinity
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: studentpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: studentpass      # Password para SYSTEM y para el usuario por defecto
      APP_USER: student                 # Crea usuario estudiante
      APP_USER_PASSWORD: studentpass
      ORACLE_DATABASE: XEPDB1           # Nombre del PDB
    ports:
      - "1521:1521"
      - "5500:5500"                     # (opcional, Oracle Enterprise Manager Express)
    volumes:
      - oracle-data:/opt/oracle/oradata # Persistencia opcional

volumes:
  oracle-data:
